### ISSUE TITLE
最近登陆可能出现   unknown flag 错误，希望升级 go-cqhttp 版本

### ISSUE THREAD

**Issue by Shimada666** [sakarie9/Go-CQHTTP-Docker#3]
登录时可能出现 unknown flag 错误的问题.
https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-beta8-fix2
此版本可以解决问题，希望能升级一下 gocqhhtp 版本

**Comment by StephenSSR** [comment]
同，求更新

**Comment by sakarie9** [comment]
更了，`docker pull xzsk2/gocqhttp-docker` 拉一下新镜像

别忘了检查一下 [配置文件](https://github.com/xzsk2/TG-EFB-QQ-Docker#%EF%B8%8F%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E6%9B%B4%E6%96%B0%E8%AD%A6%E5%91%8A%EF%B8%8F)

**Comment by StephenSSR** [comment]
额额，还是报错
```
[2021-12-13 21:21:30] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 1 次重试 
[2021-12-13 21:21:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 2 次重试 
[2021-12-13 21:21:33] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 3 次重试 
[2021-12-13 21:21:34] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 4 次重试 
[2021-12-13 21:21:37] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 5 次重试 
[2021-12-13 21:21:39] [WARNING]: 处理事件 map[interval:5000 meta_event_type:heartbeat post_type:meta_event self_id:1146781615 status:map[app_enabled:true app_good:true app_initialized:true good:true online:true plugins_good:<nil> stat:0xc0000e4498] time:1639401690] 时出现错误: runtime error: invalid memory address or nil pointer dereference 
goroutine 267 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).dispatchEventMessage.func1.1()
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:530 +0x6a
panic({0xab57c0, 0x113e5a0})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/go-cqhttp/server.(*HTTPClient).onBotPushEvent(0xc0000627d0, 0xc0003c25e0)
        github.com/Mrs4s/go-cqhttp/server/http.go:367 +0xc75
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).dispatchEventMessage.func1(0xc000028cf0)
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:535 +0xc6
created by github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).dispatchEventMessage
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:526 +0x10f
 
[2021-12-13 21:21:39] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 1 次重试
```

**Comment by tiankongsang** [comment]
上次就尝试更新来着 然后发现会报这个错误
```
 [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 1 次重试
```

哦~ 修改配置文件

**Comment by StephenSSR** [comment]
> 上次就尝试更新来着 然后发现会报这个错误
> 
> ```
>  [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 1 次重试
> ```
> 
> 哦~ 修改配置文件

请问你现在可以正常登陆了吗
